name: "EF Core Migration Changelog Analyze"
description: "Analyze CHANGELOG.md for EF Core migration and rollback files entries."
inputs:
  validation-result:
    description: "Base64-encoded validation result from EF Core Migration Changelog Check action."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Analyze validation result
      run: |
        "${GITHUB_ACTION_PATH}/scripts/analyze_ef_migration_changelog_result/analyze_ef_migration_changelog_result.sh" "${{ inputs.validation-result }}"
      shell: bash
