name: "NuGet Vulnerability Check"
description: "Checks NuGet packages for vulnerabilities"

inputs:
  excluded-packages:
    description: "Comma-separated list of packages to exclude."
    required: false
    default: ""
  path:
    description: "Relative path to the folder with solution file or project file."
    required: true
    default: "./src"

runs:
  using: "composite"
  steps:
    - name: Get vulnerabe packages
      shell: bash
      run: |
        dotnet list ${{ inputs.path }} package --include-transitive --vulnerable | tee vulnerabilities.txt

    - name: Check for vulnerable packages
      shell: bash
      run: |
        IFS=',' read -ra allowed_packages <<<"${{ inputs.excluded-packages }}";

        for package in "${allowed_packages[@]}"; do
            sed -i "/$package/d" vulnerabilities.txt
            echo "Ignoring vulnerable package: $package"
        done

        hasVulnerabePackages=$(grep -cm 1 '> ' vulnerabilities.txt || echo 0);

        echo "hasVulnerabePackages: $hasVulnerabePackages";

        rm -f vulnerabilities.txt;

        if [ $hasVulnerabePackages -gt 0 ]; then
          echo "Found vulnerabe packages! Please check output.";
          exit 1;
        fi
