name: "SQL Migration-Rollback Parity Check"
description: "Check if SQL migration and rollback scripts are in parity."
inputs:
  target-branch:
    description: "Branch to analyze for SQL migration-rollback parity."
    required: true
outputs:
  validation-result:
    description: "List of migration script files (base64-encoded) that do not have a corresponding rollback script."
    value: ${{ steps.encode_result.outputs.validation-result }}

runs:
  using: "composite"
  steps:
    - name: Find migration files
      id: find_migration_files
      run: |
        "${GITHUB_ACTION_PATH}/scripts/find_migration_scripts/find_migration_scripts.sh"
      shell: bash

    - name: Check if any migration script files found
      if: ${{ always() }}
      id: empty_check
      run: |
        "${GITHUB_ACTION_PATH}/scripts/check_empty_migration_scripts/check_empty_migration_scripts.sh"
      shell: bash

    - name: Check for corresponding rollback scripts
      id: rollback_check
      if: steps.empty_check.outputs.migration-scripts-changed == 'true'
      run: |
        "${GITHUB_ACTION_PATH}/scripts/rollback_parity_check/rollback_parity_check.sh" migration_scripts.txt > validation_result.txt
      shell: bash

    - name: Encode and set result
      id: encode_result
      run: |
        "${GITHUB_ACTION_PATH}/scripts/encode_result/encode_result.sh" validation_result.txt >> $GITHUB_OUTPUT
      shell: bash
