name: "EF Core Migration-Rollback Parity Analyze"
description: "Analyze EF Core migration-rollback parity validation results."
inputs:
  validation-result:
    description: "Base64-encoded validation result from the EF Core migration-rollback parity check."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Analyze validation result
      run: |
        "${GITHUB_ACTION_PATH}/scripts/analyze_ef_migration_rollback_parity_result/analyze_ef_migration_rollback_parity_result.sh" "${{ inputs.validation-result }}"
      shell: bash
