name: SQL Migration Rollback Parity Check

on:
  workflow_call:
    inputs:
      target_branch:
        description: "The branch to analyze for SQL migration-rollback parity."
        required: true
        type: string

jobs:
  sql_migration_rollback_parity_check:
    name: SQL Migration-Rollback Parity Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SQL migration-rollback parity check
        id: validate_sql_migration_rollback_parity
        uses: LykkeBusiness/.github/.github/actions/sql-migration-rollback-parity-check@master
        with:
          target-branch: ${{ inputs.target_branch }}

      - name: Analyze SQL migration-rollback parity check result
        id: analyze_sql_migration_rollback_parity_result
        uses: LykkeBusiness/.github/.github/actions/sql-migration-rollback-parity-analyze@master
        with:
          validation-result: ${{ steps.validate_sql_migration_rollback_parity.outputs.validation-result }}