name: SQL Migrations Check

on:
  workflow_call:
    inputs:
      base_branch:
        description: "Base branch to compare against"
        required: true
        type: string
        default: "master"
      compare_branch:
        description: "Branch to compare against the base branch"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to compare against"
        required: true
        type: string
        default: "master"
      compare_branch:
        description: "Branch to compare against the base branch"
        required: false
        type: string

jobs:
  validate_migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set comparison branch
        id: set_comparison_branch
        run: |
          compare_branch=${{ inputs.compare_branch || github.ref_name }}
          echo "Comparing $compare_branch against ${{ inputs.base_branch }}"
          echo "compare_branch=$compare_branch" >> $GITHUB_OUTPUT

      - name: Run SQL naming convention check
        uses: LykkeBusiness/.github/.github/actions/sql-naming-convention-check@master
        with:
          base-branch: ${{ inputs.base_branch }}
          compare-branch: ${{ steps.set_comparison_branch.outputs.compare_branch }}
