name: SQL Naming Convention Check

on:
  workflow_call:
    inputs:
      base_branch:
        description: "Base branch to compare against"
        required: true
        type: string
        default: "master"
      compare_branch:
        description: "Branch to compare against the base branch"
        required: true
        type: string

jobs:
  sql_naming_convention_check:
    name: SQL Naming Convention
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SQL naming convention check
        id: validate_sql_naming
        uses: LykkeBusiness/.github/.github/actions/sql-naming-convention-check@master
        with:
          base-branch: ${{ inputs.base_branch }}
          compare-branch: ${{ inputs.compare_branch }}

      - name: Analyze SQL naming convention check result
        id: analyze_sql_naming_result
        uses: LykkeBusiness/.github/.github/actions/sql-naming-convention-analyze@master
        with:
          validation-result: ${{ steps.validate_sql_naming.outputs.validation-result }}