name: SQL Check

on:
  workflow_call:
    inputs:
      base_branch:
        description: "Base branch to compare against"
        required: true
        type: string
        default: "master"
      compare_branch:
        description: "Branch to compare against the base branch"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to compare against"
        required: true
        type: string
        default: "master"
      compare_branch:
        description: "Branch to compare against the base branch"
        required: false
        type: string

jobs:
  sql_naming_convention_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set comparison branch
        id: set_comparison_branch
        run: |
          compare_branch=${{ inputs.compare_branch || github.ref_name }}
          echo "Comparing $compare_branch against ${{ inputs.base_branch }}"
          echo "compare_branch=$compare_branch" >> $GITHUB_OUTPUT

      - name: Run SQL naming convention check
        id: validate_sql_naming
        uses: LykkeBusiness/.github/.github/actions/sql-naming-convention-check@master
        with:
          base-branch: ${{ inputs.base_branch }}
          compare-branch: ${{ steps.set_comparison_branch.outputs.compare_branch }}

      - name: Analyze SQL naming convention check result
        id: analyze_sql_naming_result
        uses: LykkeBusiness/.github/.github/actions/sql-naming-convention-analyze@master
        with:
          validation-result: ${{ steps.validate_sql_naming.outputs.validation-result }}

      - name: Run SQL migration-rollback parity check
        id: validate_sql_migration_rollback_parity
        uses: LykkeBusiness/.github/.github/actions/sql-migration-rollback-parity-check@master
        with:
          target-branch: ${{ steps.set_comparison_branch.outputs.compare_branch }}

      - name: Analyze SQL migration-rollback parity check result
        id: analyze_sql_migration_rollback_parity_result
        uses: LykkeBusiness/.github/.github/actions/sql-migration-rollback-parity-analyze@master
        with:
          validation-result: ${{ steps.validate_sql_migration_rollback_parity.outputs.validation-result }}

      - name: Run EF Core migration-rollback parity check
        id: validate_ef_migration_rollback_parity
        uses: LykkeBusiness/.github/.github/actions/ef-migration-rollback-parity-check@master
        with:
          base-branch: ${{ inputs.base_branch }}
          compare-branch: ${{ steps.set_comparison_branch.outputs.compare_branch }}
      
      - name: Analyze EF Core migration-rollback parity check result
        id: analyze_ef_migration_rollback_parity_result
        uses: LykkeBusiness/.github/.github/actions/ef-migration-rollback-parity-analyze@master
        with:
          validation-result: ${{ steps.validate_ef_migration_rollback_parity.outputs.validation-result }}